export const CASE_STATUS = {
  OPEN: "OPEN",
  BID_SELECTED: "BID_SELECTED",
  ESCROW_PENDING: "ESCROW_PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  VERIFYING: "VERIFYING",
  COMPLETED: "COMPLETED",
  DISPUTED: "DISPUTED",
} as const

export const ESCROW_STATUS = {
  PENDING_SIGNATURE: "PENDING_SIGNATURE",
  FUNDED: "FUNDED",
  RELEASE_PENDING: "RELEASE_PENDING",
  RELEASED: "RELEASED",
  DISPUTED: "DISPUTED",
  FAILED: "FAILED",
} as const

export type CaseStatus = keyof typeof CASE_STATUS
export type EscrowStatus = keyof typeof ESCROW_STATUS